W820NB supported
wh201906/mEDIFIER pull request #7
Opened 2024-09-19 08:58 UTC by BreakpointDebug1234

Tested W820NB as a generic device. Everything seems to work except the sound effect panel which doesn't seem to do anything.

Tested with firmware version: 01.00.01

I had to use google translate for Simplified Chinese readme.

2024-09-19 14:56 UTC, wh201906 commented
Thanks for your work! I can add a dedicated profile for W820NB before merging this PR.
According to some reviews, it seems W820NB doesn't support Sound Effect so it's reasonable these functions don't work.

I also found the `Control Settings` panel might be unavailable for W820NB. Could you please help me to test it?
(For W820NB Double Gold, when clicking the Bluetooth button, the modes will only switch among the selected modes in the `Control Settings`)

2024-09-25 10:58 UTC, TheAirBlow commented
I'm currently working on my own solution called `remEDIFIER`. You can get the feature flags by sending `D8`, values of which are parsed by the Edifier ConneX app inside `com.edifier.lib_connect.models.D8Bean`.

2024-09-25 11:08 UTC, wh201906 commented
Never tried Edifier ConneX app before. Thanks for your information! @TheAirBlow

2024-09-25 15:56 UTC, TheAirBlow commented
> Never tried Edifier ConneX app before. Thanks for your information! @TheAirBlow

Is Edifier Connect obfuscated? I would assume both of them would use the same libraries, as `lib_connect`, `lib_common` and etc. would suggest.

2024-09-25 15:57 UTC, TheAirBlow commented
Also, the way the app identifies the headphones without communicating directly is getting manufacturer specific data from `EDIFIER BLE` device, over which you can also communicate when the device is connected over USB.

2024-09-26 04:40 UTC, wh201906 commented
> Is Edifier Connect obfuscated?

I'm not sure. I get the command set by checking the Logcat output and Edifier Connect prints every command there. Does Edifier ConneX print the command in the Logcat output?

2024-09-26 11:27 UTC, BreakpointDebug1234 commented
> Thanks for your work! I can add a dedicated profile for W820NB before merging this PR. According to some reviews, it seems W820NB doesn't support Sound Effect so it's reasonable these functions don't work.
> 
> I also found the `Control Settings` panel might be unavailable for W820NB. Could you please help me to test it? (For W820NB Double Gold, when clicking the Bluetooth button, the modes will only switch among the selected modes in the `Control Settings`)

Tested and looks like `Control Settings` doesn't do anything as well but that can be disabled too.

2024-09-26 11:33 UTC, wh201906 commented
> Tested and looks like `Control Settings` doesn't do anything as well but that can be disabled too.

So no matter which modes are selected in `Control Settings`, the modes will only switch to a fixed set of them when pressing the Bluetooth button, right?

2024-09-26 11:46 UTC, BreakpointDebug1234 commented
> > Tested and looks like `Control Settings` doesn't do anything as well but that can be disabled too.
> 
> So no matter which modes are selected in `Control Settings`, the modes will only switch to a fixed set of them when pressing the Bluetooth button, right? Could you please tell me what will you hear when pressing the Bluetooth button? Does the sequence change if you select different modes in `Control Settings?`

Oh, I now understand what's supposed to do. Sadly I can't use the physical buttons on the headphones due a hardware issue (volume down button has broken and for some reason that renders the Bluetooth button unusable too) 

Btw, thanks for the app, I can now get around these issues without having to use the edifer app plus I can use it on PC too.

2024-09-26 11:48 UTC, wh201906 commented
I see. I will also disable the `Control Settings` for W820NB. If someone reports it is available, I will enable it again.

2024-09-26 12:31 UTC, TheAirBlow commented
> > Is Edifier Connect obfuscated?
> 
> I'm not sure. I get the command set by checking the Logcat output and Edifier Connect prints every command there. Does Edifier ConneX print the command in the Logcat output?

Didn't check. I did decompile it with Jadx though, and looks like there is a lot of debug logging in here.

2024-09-26 12:32 UTC, TheAirBlow commented
It's probably better to just decompile it and look through the source code than trying to crack your head trying to understand what all of those binary packets mean.

2024-09-26 12:39 UTC, wh201906 commented on Qt/devices/deviceinfo.json
> +    "w820": {
Thanks! Please use a similar name style here.
```suggestion
    "w820nb": {
```

2024-09-26 12:42 UTC, wh201906 commented on README_zh_CN.md
> ++ 仅测试了 W820NB、W820NB双金标版 和 W200BT Plus
Thank you for using google translate for it! However, I prefer to not make unnecessary changes here.
```suggestion
+ 仅测试过 W820NB、W820NB双金标版 和 W200BT Plus  
```

2024-09-26 12:46 UTC, wh201906 commented on README_zh_CN.md
> +  (也许可以在 W820NB Plus 上使用)
For the same reason above
```suggestion
  (也许能用在 W820NB Plus 上)  
```

2024-09-26 12:46 UTC, wh201906 requested changes
Thanks for your work!

2024-09-26 13:08 UTC, wh201906 approved these changes
Great. Thanks for your work!

2024-09-26 13:10 UTC, merged